import { Container, Graphics } from "pixi.js";
import WavesManager from "./wavesManager.ts";
import Mod from "../mod.ts";
import { State } from "../states/state.ts";
import AssetsManager from "./assetsManager.ts";
import Pacman from "../../../../../../../scripts/characters/pacman.ts";
import Ghost from "../../../../../../../scripts/characters/ghost.ts";
import GameCoordinator from "../../../../../../../scripts/core/gameCoordinator.ts";
import RegisterListeners from "./registerListeners.ts";
declare class Flood extends Mod implements RegisterListeners {
    #private;
    name: string;
    width: number;
    maxHeight: number;
    tileSize: number;
    container: Container;
    gp: Graphics;
    am: AssetsManager;
    wavesManager: WavesManager;
    pacman: Pacman;
    ghosts: Ghost[];
    states: State[];
    state: State;
    waveIntervalMin: number;
    waveIntervalMax: number;
    pacmanMaxBreathing: number;
    ghostsMaxBreathing: number;
    constructor(gameCoordinator: GameCoordinator);
    initialize(): Promise<void>;
    registerListeners(): void;
    changeState(state: number): void;
    start(): void;
    stop(): void;
    generateWave(timeToStartMS?: number): void;
    reset(): void;
    update(elapsedMs: number): void;
    draw(): void;
}
export default Flood;
//# sourceMappingURL=flood.d.ts.map