import { Texture } from "pixi.js";
import GameCoordinator from "../core/gameCoordinator.ts";
declare class Debugger {
    gc: GameCoordinator;
    overflowMask: any;
    mazeDiv: any;
    mazeArray: any;
    tileSize: number;
    scale: number;
    pacmanImmortal: boolean;
    printMazeGrid: boolean;
    infoPanel: any;
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    shouldPrintGrid: boolean;
    enableBoundsAndHitBoxes: boolean;
    printing: any;
    showConsole: boolean;
    consoleBuffer: string[];
    fps: number;
    lastFrameTime: number;
    constructor(gameCoordinator: GameCoordinator);
    handleInput(): void;
    createCanvas(): void;
    moveInUnits(direction: string, units: number): void;
    animate(): void;
    printGrid(): void;
    clearGrid(): void;
    configInfoPanel(): void;
    makePacmanImortal(isImmortal: boolean): void;
    drawEntities(isDraw: boolean): void;
    moveEntities(): void;
    startWave(): void;
    drawBoundsAndHitBoxes(onlyMovableEntities: boolean): void;
    toggleConsole(): void;
    consoleLog(message: string): void;
    clearConsole(): void;
    private updateFps;
    private getConsoleData;
    private wrapText;
    printConsole(): void;
    getImageData(texture: Texture): void;
    notifyPacmanMovement(): void;
    _notify(functionName: any): void;
    _notify2(functionName: string): void;
}
export default Debugger;
//# sourceMappingURL=debugger.d.ts.map